USE [hr-access]
GO

IF NOT EXISTS (SELECT * FROM master.dbo.syslogins) 
BEGIN
CREATE LOGIN HRACCESS_LOGIN WITH PASSWORD = 'HRACCESS'
END
GO

CREATE USER [HRACCESS_USER] FOR LOGIN [HRACCESS_LOGIN]
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'HRACCESS')
BEGIN
EXEC('CREATE SCHEMA HRACCESS')
END
GO

CREATE SEQUENCE [HRACCESS].[HIBERNATE_SEQUENCE] START WITH 1000 INCREMENT BY 1;
GO

CREATE TABLE [HRACCESS].[DEPARTMENT] 
(
	[ID] [INTEGER] NOT NULL, 
	[NAME] [VARCHAR](255) NOT NULL, 
	PRIMARY KEY (ID)
)

CREATE TABLE [HRACCESS].[EMPLOYEE] 
(
	[ID] [INTEGER] NOT NULL, 
	[BONUS] [FLOAT], 
	[FIRST_NAME] [VARCHAR](255) NOT NULL, 
	[LAST_NAME] [VARCHAR](255) NOT NULL, 
	[MANAGER_ID] [INTEGER] NOT NULL, 
	[SALARY] [FLOAT], 
	[VACATION_BALANCE] [INTEGER], 
	[DEPARTMENT_ID] [INTEGER], 
	[ROLE_ID] [INTEGER], 
	[USER_ID] [INTEGER], 
	PRIMARY KEY (ID)
)

CREATE TABLE [HRACCESS].[EMPLOYEE_FINANCES] 
(
	[EMPLOYEE_ID] [INTEGER] NOT NULL, 
	[FINANCES_ID] [INTEGER] NOT NULL
)

CREATE TABLE [HRACCESS].[FINANCE]
(
	[ID] [INTEGER] NOT NULL, 
	[ADDED] [DATETIME] NOT NULL, 
	[TYPE] [VARCHAR](255) NOT NULL, 
	[OLD_VALUE] [FLOAT] NOT NULL, 
	[NEW_VALUE] [FLOAT] NOT NULL, 
	PRIMARY KEY (ID)
)

CREATE TABLE [HRACCESS].[ROLE] 
(
	[ID] [INTEGER] NOT NULL, 
	[TYPE] [VARCHAR] (255) NOT NULL, 
	PRIMARY KEY (ID)
)

CREATE TABLE [HRACCESS].[USER] 
(
	[ID] [INTEGER] NOT NULL, 
	[USER_ENABLED] [BIT] NOT NULL, 
	[PASSWORD] [VARCHAR](255) NOT NULL, 
	[PRIVILEGE] [VARCHAR](255) NOT NULL, 
	[USER_NAME] [VARCHAR](255) NOT NULL, 
	[FAILED_COUNT] [INTEGER], 
	PRIMARY KEY (ID)
)

ALTER TABLE [HRACCESS].[EMPLOYEE_FINANCES] ADD CONSTRAINT UK_O7VHJFHUJMMDWM5EVQRN26GCV UNIQUE (FINANCES_ID);
ALTER TABLE [HRACCESS].[USER] ADD CONSTRAINT UK_LQJRCOBRH9JC8WPCAR64Q1BFH UNIQUE (USER_NAME);
ALTER TABLE [HRACCESS].[EMPLOYEE] ADD CONSTRAINT FKBEJTWVG9BXUS2MFFSM3SWJ3U9 FOREIGN KEY (DEPARTMENT_ID) REFERENCES [HRACCESS].[DEPARTMENT];
ALTER TABLE [HRACCESS].[EMPLOYEE] ADD CONSTRAINT FK3046KVJYYSQ288VY3LSBTC9NW FOREIGN KEY (ROLE_ID) REFERENCES [HRACCESS].[ROLE];
ALTER TABLE [HRACCESS].[EMPLOYEE] ADD CONSTRAINT FK6LK0XML9R7OKJDQ0ONKA4YTJU FOREIGN KEY (USER_ID) REFERENCES [HRACCESS].[USER];
ALTER TABLE [HRACCESS].[EMPLOYEE_FINANCES] ADD CONSTRAINT FKAOS1CEC834L39U9IS530XG40K FOREIGN KEY (FINANCES_ID) REFERENCES [HRACCESS].[FINANCE];
ALTER TABLE [HRACCESS].[EMPLOYEE_FINANCES] ADD CONSTRAINT FK1LD4FJ9728M64PP9TPUIP9GUV FOREIGN KEY (EMPLOYEE_ID) REFERENCES [HRACCESS].[EMPLOYEE];

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON [HRACCESS].[EMPLOYEE] TO HRACCESS_USER; 
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON [HRACCESS].[EMPLOYEE_FINANCES] TO HRACCESS_USER;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON [HRACCESS].[FINANCE] TO HRACCESS_USER;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON [HRACCESS].[ROLE] TO HRACCESS_USER;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON [HRACCESS].[USER] TO HRACCESS_USER;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON [HRACCESS].[DEPARTMENT] TO HRACCESS_USER;

INSERT INTO [HRACCESS].[DEPARTMENT] VALUES (1, 'HR');
INSERT INTO [HRACCESS].[DEPARTMENT] VALUES (2, 'IT');

INSERT INTO [HRACCESS].[ROLE] VALUES (1, 'MANAGER');
INSERT INTO [HRACCESS].[ROLE] VALUES (2, 'EMPLOYEE');